// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: wal.proto

package walpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecordKind describes the logical type of a WAL record.
type RecordKind int32

const (
	RecordKind_UNSPECIFIED    RecordKind = 0
	RecordKind_SEGMENT_HEADER RecordKind = 1
	RecordKind_DATA           RecordKind = 2
	RecordKind_ROTATION       RecordKind = 3
	RecordKind_CHECKPOINT     RecordKind = 4
)

// Enum value maps for RecordKind.
var (
	RecordKind_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SEGMENT_HEADER",
		2: "DATA",
		3: "ROTATION",
		4: "CHECKPOINT",
	}
	RecordKind_value = map[string]int32{
		"UNSPECIFIED":    0,
		"SEGMENT_HEADER": 1,
		"DATA":           2,
		"ROTATION":       3,
		"CHECKPOINT":     4,
	}
)

func (x RecordKind) Enum() *RecordKind {
	p := new(RecordKind)
	*p = x
	return p
}

func (x RecordKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordKind) Descriptor() protoreflect.EnumDescriptor {
	return file_wal_proto_enumTypes[0].Descriptor()
}

func (RecordKind) Type() protoreflect.EnumType {
	return &file_wal_proto_enumTypes[0]
}

func (x RecordKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// RecordHeader describes metadata that applies to a single WAL record.
type RecordHeader struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Lsn         uint64                 `protobuf:"fixed64,1,opt,name=lsn"`
	xxx_hidden_PreviousLsn uint64                 `protobuf:"fixed64,2,opt,name=previous_lsn,json=previousLsn"`
	xxx_hidden_Timestamp   uint64                 `protobuf:"fixed64,3,opt,name=timestamp"`
	xxx_hidden_Checksum    uint32                 `protobuf:"fixed32,4,opt,name=checksum"`
	xxx_hidden_Magic       uint32                 `protobuf:"fixed32,5,opt,name=magic"`
	xxx_hidden_Version     uint32                 `protobuf:"fixed32,6,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RecordHeader) Reset() {
	*x = RecordHeader{}
	mi := &file_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordHeader) ProtoMessage() {}

func (x *RecordHeader) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordHeader) GetLsn() uint64 {
	if x != nil {
		return x.xxx_hidden_Lsn
	}
	return 0
}

func (x *RecordHeader) GetPreviousLsn() uint64 {
	if x != nil {
		return x.xxx_hidden_PreviousLsn
	}
	return 0
}

func (x *RecordHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *RecordHeader) GetChecksum() uint32 {
	if x != nil {
		return x.xxx_hidden_Checksum
	}
	return 0
}

func (x *RecordHeader) GetMagic() uint32 {
	if x != nil {
		return x.xxx_hidden_Magic
	}
	return 0
}

func (x *RecordHeader) GetVersion() uint32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *RecordHeader) SetLsn(v uint64) {
	x.xxx_hidden_Lsn = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *RecordHeader) SetPreviousLsn(v uint64) {
	x.xxx_hidden_PreviousLsn = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *RecordHeader) SetTimestamp(v uint64) {
	x.xxx_hidden_Timestamp = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *RecordHeader) SetChecksum(v uint32) {
	x.xxx_hidden_Checksum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *RecordHeader) SetMagic(v uint32) {
	x.xxx_hidden_Magic = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *RecordHeader) SetVersion(v uint32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *RecordHeader) HasLsn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RecordHeader) HasPreviousLsn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RecordHeader) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RecordHeader) HasChecksum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RecordHeader) HasMagic() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *RecordHeader) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *RecordHeader) ClearLsn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Lsn = 0
}

func (x *RecordHeader) ClearPreviousLsn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PreviousLsn = 0
}

func (x *RecordHeader) ClearTimestamp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Timestamp = 0
}

func (x *RecordHeader) ClearChecksum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Checksum = 0
}

func (x *RecordHeader) ClearMagic() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Magic = 0
}

func (x *RecordHeader) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Version = 0
}

type RecordHeader_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Log Sequence Number (LSN) of this record.
	Lsn *uint64
	// LSN of the previous record in the log.
	PreviousLsn *uint64
	// Wall clock time when this record was created.
	Timestamp *uint64
	// Header checksum, used to detect corruption of the header fields.
	Checksum *uint32
	// Magic constant to quickly verify you're reading a valid WAL record.
	Magic *uint32
	// Version of the WAL on disk format.
	Version *uint32
}

func (b0 RecordHeader_builder) Build() *RecordHeader {
	m0 := &RecordHeader{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Lsn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Lsn = *b.Lsn
	}
	if b.PreviousLsn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_PreviousLsn = *b.PreviousLsn
	}
	if b.Timestamp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Timestamp = *b.Timestamp
	}
	if b.Checksum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Checksum = *b.Checksum
	}
	if b.Magic != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Magic = *b.Magic
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

// Record is the physical unit written to and read from the WAL stream.
type Record struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind        RecordKind             `protobuf:"varint,1,opt,name=kind,enum=walpb.v1.RecordKind"`
	xxx_hidden_Checksum    uint32                 `protobuf:"varint,2,opt,name=checksum"`
	xxx_hidden_Payload     []byte                 `protobuf:"bytes,3,opt,name=payload"`
	xxx_hidden_Padded      []byte                 `protobuf:"bytes,4,opt,name=padded"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Record) GetKind() RecordKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Kind
		}
	}
	return RecordKind_UNSPECIFIED
}

func (x *Record) GetChecksum() uint32 {
	if x != nil {
		return x.xxx_hidden_Checksum
	}
	return 0
}

func (x *Record) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *Record) GetPadded() []byte {
	if x != nil {
		return x.xxx_hidden_Padded
	}
	return nil
}

func (x *Record) SetKind(v RecordKind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Record) SetChecksum(v uint32) {
	x.xxx_hidden_Checksum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Record) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Record) SetPadded(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Padded = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Record) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Record) HasChecksum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Record) HasPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Record) HasPadded() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Record) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Kind = RecordKind_UNSPECIFIED
}

func (x *Record) ClearChecksum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Checksum = 0
}

func (x *Record) ClearPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Payload = nil
}

func (x *Record) ClearPadded() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Padded = nil
}

type Record_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Logical kind of this record (see RecordKind).
	Kind *RecordKind
	// Checksum for the record contents.
	Checksum *uint32
	// Actual data carried by the record.
	Payload []byte
	// Optional padding bytes to align records on disk.
	Padded []byte
}

func (b0 Record_builder) Build() *Record {
	m0 := &Record{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.Checksum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Checksum = *b.Checksum
	}
	if b.Payload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Payload = b.Payload
	}
	if b.Padded != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Padded = b.Padded
	}
	return m0
}

var File_wal_proto protoreflect.FileDescriptor

const file_wal_proto_rawDesc = "" +
	"\n" +
	"\twal.proto\x12\bwalpb.v1\"\xad\x01\n" +
	"\fRecordHeader\x12\x10\n" +
	"\x03lsn\x18\x01 \x01(\x06R\x03lsn\x12!\n" +
	"\fprevious_lsn\x18\x02 \x01(\x06R\vpreviousLsn\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x06R\ttimestamp\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\aR\bchecksum\x12\x14\n" +
	"\x05magic\x18\x05 \x01(\aR\x05magic\x12\x18\n" +
	"\aversion\x18\x06 \x01(\aR\aversion\"\x80\x01\n" +
	"\x06Record\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.walpb.v1.RecordKindR\x04kind\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\rR\bchecksum\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x16\n" +
	"\x06padded\x18\x04 \x01(\fR\x06padded*Y\n" +
	"\n" +
	"RecordKind\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEGMENT_HEADER\x10\x01\x12\b\n" +
	"\x04DATA\x10\x02\x12\f\n" +
	"\bROTATION\x10\x03\x12\x0e\n" +
	"\n" +
	"CHECKPOINT\x10\x04B!Z\x1fgithub.com/iamBelugax/wal;walpbb\beditionsp\xe9\a"

var file_wal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wal_proto_goTypes = []any{
	(RecordKind)(0),      // 0: walpb.v1.RecordKind
	(*RecordHeader)(nil), // 1: walpb.v1.RecordHeader
	(*Record)(nil),       // 2: walpb.v1.Record
}
var file_wal_proto_depIdxs = []int32{
	0, // 0: walpb.v1.Record.kind:type_name -> walpb.v1.RecordKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wal_proto_init() }
func file_wal_proto_init() {
	if File_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_proto_rawDesc), len(file_wal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_proto_goTypes,
		DependencyIndexes: file_wal_proto_depIdxs,
		EnumInfos:         file_wal_proto_enumTypes,
		MessageInfos:      file_wal_proto_msgTypes,
	}.Build()
	File_wal_proto = out.File
	file_wal_proto_goTypes = nil
	file_wal_proto_depIdxs = nil
}
